---
# Instala modulo do docker com o pip para a manager iniciar o swarm com o modulo docker_swarm
- name: Instala pip3 na manager
  apt:
    update_cache: yes
    name: python3-pip
    state: present
  when: ansible_os_family == 'Debian'

- name: Instala modulo do docker na manager
  pip:
    name: docker

- name: iniciando swarm manager
  docker_swarm:
    state: present
    # advertise_addr: "{{ ansible_default_ipv4.alias }}"
  # register: swarm_info

- name: Registrando join token do swarm
  command: docker swarm join-token worker -q
  register: swarm_token_worker

- name: Registrando manager uri do swarm
  shell:  docker swarm join-token worker | grep docker | awk '{print $6}'
  register: swarm_manager_uri
