---
- name: Criacao da AMI
  hosts: localhost
  gather_facts: true
  roles:
    - imagem

- name: Provisionando maquinas na AWS
  hosts: localhost
  gather_facts: true
  roles:
    - aws

- name: Atualiza inventario
  hosts: localhost
  gather_facts: false
  tasks:
  - meta: refresh_inventory

- name: Wait vms go up
  hosts: maquinas
  gather_facts: False
  tasks:
    - wait_for_connection:
        timeout: 300

- name: Checking if Cloud Init has finished
  hosts: maquinas
  gather_facts: False
  become: yes
  tasks:
    - cloud_init_data_facts:
        filter: status
      register: res
      until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
      retries: 50
      delay: 5

- name: Instalando e iniciando cluster Swarm
  hosts: manager
  become: yes
  gather_facts: true
  roles:
    - docker-manager

- name: Garantindo autoscaling
  hosts: localhost
  gather_facts: false
  roles:
    - autoscaling

- name: Instalação harbor
  hosts: harbor
  become: yes
  gather_facts: true
  roles:
    - harborregistry
