---
# tasks file for aws
- name: garante vpc e subnet
  include: rede.yml

- name: garante chave de ssh
  include: chave.yml

- name: garante security group
  include: security_group.yml

- name: garantindo infraestrutura na aws
  include: manager.yml

- name: garantindo registry na aws
  include: harbor.yml
