---
# tasks file for imagem
- name: Destroi imagem e snapshot existentes
  import_tasks: "destroi_imagem_aws.yml"

- name: download do packer
  unarchive:
    src: https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip
    dest: packer
    remote_src: yes

- name:  executar packer
  shell: "./packer build packer_aws.json"
  args:
    chdir: "packer"
